name: Trigger EndPoint Job on a CRON Schedule

on:
  schedule:
    # Runs "every 5 minutes" (see https://crontab.guru)
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Trigger Create Job
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
          timezoneMacos: "Asia/Taipei"
          timezoneWindows: "Taipei Standard Time"
      - name: cURL request
        # Hit the webhook endpoint to trigger job from the "main" branch
        run: |
          curl --request POST \
            --url ${{ secrets.ENDPOINT }} \
            --header 'Content-Type: application/json' \
            --data '{
            "username": ${{ secrets.TARGET }}
          }'